## Домашнє завдання 3.1. Тема 3. Основи роботи з бібліотеками Numpy, Pandas, Matplotlib, Plotly
Виконавець: Черемісін

### 1. Створення масивів

In [ ]:
# Створіть (кожен пункт оцінюється в 0.5 бала):

# Масив зі списку [5, 15, 25, 35, 45]
# Масив з нулів розміром 7
# Масив з одиниць розміром 6
# Масив з числами від 10 до 19 використовуючи np.arange()

In [2]:
import numpy as np

In [14]:
arr_1 = np.array ([5, 15, 25, 35, 45])
print(arr_1) 

[ 5 15 25 35 45]


In [10]:
arr_zero = np.zeros (7)
print(arr_zero) 

[0. 0. 0. 0. 0. 0. 0.]


In [11]:
arr_one = np.ones (6)
print(arr_one) 

[1. 1. 1. 1. 1. 1.]


In [13]:
# до 19 включно
arr_line = np.arange (10, 20)
print(arr_line) 

[10 11 12 13 14 15 16 17 18 19]


In [14]:
# до 19 не включно
arr_line = np.arange (10, 19)
print(arr_line) 

[10 11 12 13 14 15 16 17 18]


### 2. Базові операції

In [ ]:
# СтСтворіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

# Виконайте наступні операції над оригінальним масивом і запишіть у нову змінну результат 
# (кожен пункт оцінюється в 0.5 бала):

# Помножте всі елементи на 2
# Додайте до всіх елементів 10
# Піднесіть всі елементи до квадрату
# Обчисліть квадратний корінь з усіх елементів
# Виведіть результат виконання кожної операції.

In [15]:
arr2 = np.array ([12, 24, 36, 48, 60])
print(arr2) 

[12 24 36 48 60]


In [17]:
arr_mult = 2 * arr2
print(arr_mult)

[ 24  48  72  96 120]


In [18]:
arr_plus = 10 + arr2
print(arr_plus)

[22 34 46 58 70]


In [20]:
arr_deg = arr2 ** 2
print(arr_deg)

[ 144  576 1296 2304 3600]


In [22]:
arr_roo = np.sqrt(arr2) 
print(arr_roo)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]


In [23]:
print(arr2) 
print(arr_mult)
print(arr_plus)
print(arr_deg)
print(arr_roo)

[12 24 36 48 60]
[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]


### 3. Статистичні функції

In [ ]:
# Створіть Numpy-масив data зі значеннями [18, 27, 33, 41, 52, 68, 79].

# Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):

# Середнє значення
# Мінімум
# Максимум
# Суму всіх елементів

In [9]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(data)

[18 27 33 41 52 68 79]


In [10]:
aver = data.mean()
print(aver)

45.42857142857143


In [11]:
minim = data.min()
print(minim)

18


In [12]:
maxim = data.max()
print(maxim)

79


In [13]:
summ = data.sum()
print(summ)

318


### 4. Індексація

In [ ]:
# Створіть Numpy-масив arr зі значеннями [15, 22, 35, 44, 58, 67].

# Виведіть (кожен пункт оцінюється в 0.5 бала):

# Перший елемент
# Останній елемент
# Елементи з індексами 1 до 3
# Елементи більші за 40

In [26]:
arr = np.array([15, 22, 35, 44, 57, 67])
print(arr)

[15 22 35 44 57 67]


In [17]:
print(arr[0])

15


In [19]:
print(arr[-1])

67


In [21]:
# Елементи з індексами 1 до 3
print(arr[1:3])

[22 35]


In [22]:
# Елементи з індексами 1 до 3 включно
print(arr[1:4])

[22 35 44]


In [30]:
over_40 = arr[arr > 40]
print(over_40)

[44 57 67]


### 5. Двовимірні масиви

In [ ]:
# Задано матрицю 3x3.

# Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):

# Виведіть форму (shape) матриці
# Виведіть перший рядок
# Виведіть другу колонку
# Обчисліть суму всіх елементів
# Обчисліть середнє всіх елементів

In [31]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [32]:
print(matrix.shape)

(3, 3)


In [33]:
print(matrix[0])

[2 4 6]


In [34]:
print(matrix[:, 1])

[ 4 10 16]


In [35]:
mat_sum = matrix.sum()
print(mat_sum)

90


In [37]:
mat_aver = matrix.mean()
print(mat_aver)

10.0
